const EngEmotions = {
    ecstasy : "",
    admiration: "",
    terror: "",
    amazement: "",
    grief: "",
    loathing: "",
    rage: "",
    vigilance: "",
    joy: "",
    trust: "",
    fear: "",
    surprise: "",
    sadness: "",
    disgust: "",
    anger: "",
    anticipation: "",
    serenity: "",
    acceptance: "",
    apprehension: "",
    distraction: "",
    pensiveness: "",
    boredom: "",
    annoyance: "",
    interest: "",
    love: "",
    submission: "",
    awe: "",
    disapproval: "",
    emorse: "",
    contempt: "",
    aggressiveness: "",
    optimistm: "",
    total: ""
  }

  module.exports = {EngEmotions};